language: java
jdk:
- openjdk7
notifications:
  email:
  - soiland-reyes@cs.manchester.ac.uk
env:
  global:
    secure: UipjZs2MK2BPl0dBXVvUeTO7YX0orEadW5OgkwIiEXRqdfIMkqtUvISA8PXsqE5ybFdIWP5+9vJITsD8YVMit62kjujubyPMQ8ixPPj9YWeqHFpBKVu2YnDFE2C4lUKCNG01noJVLRc4CUQA55d6zt0AgPamgBesTyE2tnE8hV4=
after_script: mvn deploy
